version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  insecure-external-code-execution: allow
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
