--- 
app_host: "https://paf-tra.aws.defra.cloud"
custom: 
  urls: 
    front_office: "https://paf-tra.aws.defra.cloud/users/sign_in"
  user_accounts:
    rma:
      username: paf1@example.com
    pso:
      username: paf3@example.com
    area:
      username: paf4@example.com
display_failures: true
driver: chrome
headless: false
max_wait_time: 10
pause: 0
print_progress: false
stop_on_error: true
